### PR TITLE
Add M2.4 and php 7.4

### PR DESCRIPTION
**Pull request by codedge**
Please make sure these boxes are checked before submitting your PR - thank you!

- [x] Pull request is based against develop branch
- [x] README.md reflects changes (if applicable)
- [x] New files contain a license header

### Issue

This PR fixes issue #174  .

### CODE REVIEW

**Comment by sprankhub** [comment]
@frostblogNet, could you have a look at the failing builds?

**Comment by sprankhub** [comment]
@codedge thanks for the PR! Did you already test the module manually with 2.4? What were the results?

**Comment by codedge** [comment]
Not yet, but I hope I can make it today. I'll let you know about the results and will add changes to this PR if needed.

**Comment by sprankhub** [comment]
@codedge were you able to test in the meantime?

**Comment by codedge** [comment]
@sprankhub Sorry, for the delay. Tested it today, without issues.

* Updated to 2.4
* Compiling works
* All pages and translations do still work

I couldn't spot any issues with the module.

**Comment by sprankhub** [comment]
Thanks for the confirmation, @codedge. I would like to merge this, but the build still fails. All jobs failed initially due to missing Composer credentials during the `composer create-project` call. After multiple manual restarts, it worked for all jobs but the 2.4 job. I currently have no idea why :-/

**Comment by codedge** [comment]
Hmm.. ok. Let me know if I can help somewhere.

**Comment by codedge** [comment]
Very strange. I just tried to pin Magento to a fixed version, `2.4.0`, and let it run - but still, it fails before even trying to install it. Only the 2.4 is affected.

Any idea how to debug that?

**Comment by sprankhub** [comment]
@codedge thanks for your work on this! There was a bit more work needed. Closing this in favour of #183.

**Pull request closed without merging**
