### PR TITLE
Hardened product list plugin against missing block

### PR DESCRIPTION
**Pull request by yariksheptykin**
Hi guys!

On my installation firegento-magesetup2 would break the search results page with an exception about calling `setProduct` on `boolean` in `ListProductPlugin`. This only happens in production mode with `di` compiled.

The patch I submit adds a simple check if the block exists and a test for it. It also adds delivery data to the search result page to make rendering of delivery info in search results possible.

### CODE REVIEW

**Comment by lgt** [comment]
is there a way to override with this changes till is getting merged?

**Comment by yariksheptykin** [comment]
@lgt, you could try to add this:
```
    <body>
        <block class="FireGento\MageSetup\Block\Product\Delivery" name="product.info.delivery" as="simple" template="FireGento_MageSetup::product/list/delivery.phtml">
            <arguments>
                <argument name="at_call" xsi:type="string">getDeliveryTime</argument>
                <argument name="at_code" xsi:type="string">delivery_time</argument>
                <argument name="css_class" xsi:type="string">delivery_time</argument>
                <argument name="at_label" xsi:type="string">Delivery Time </argument>
                <argument name="add_attribute" xsi:type="string">itemprop="delivery_time "</argument>
            </arguments>
    </block>
```
to `view/frontend/layout/catalogsearch_result_index.xml` in your theme or module. This should fix the issue with missing block.

**Comment by yariksheptykin** [comment]
@lgt, or, if you use composer, you can pull the package from my fork:
```
    "repositories": {
        "firegento_magesetup": {
            "type": "vcs",
            "url": "https://github.com/yariksheptykin/firegento-magesetup2.git"
        }
    },
```
```
    "require": {
       "firegento/magesetup2": "dev-develop"
    }
```
The fork is basically 1 to 1 except for the plugin patch.
But use it at your own risk. I cannot guarantee that the fork will keep up with the upstream.

**Comment by therouv** [comment]
@yariksheptykin Thanks!

**Comment by lgt** [comment]
fixed I could override it!

**Comment by yariksheptykin** [comment]
The patch has been just merged. I recommend updating composer dependencies
in favor of XML workaround. Also, don't forget to delete XML code after you
update the lib to avoid unpredictable behavior.

**Pull request merged**
